services:
  phone-directory-app:
    image: phone-directory-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=phonedirectory;Username=postgres;Password=12345678
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: phonedirectory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d

volumes:
  db-data: